/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author aksha
 */
public class JPanel_Library_enterprise_Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admission_enterprise
     */
    public JPanel_Library_enterprise_Admin() {
        initComponents();
        bookDirectory.setVisible(false);
        libraryRoomBooking.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneAdms = new javax.swing.JLayeredPane();
        bookDirectory = new javax.swing.JPanel();
        description = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librarytable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        bookname = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        libraryRoomBooking = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        libraryroommaintable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        roomname = new javax.swing.JComboBox<>();
        slots = new javax.swing.JComboBox<>();
        Student_button = new javax.swing.JButton();
        Course_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bookDirectory.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Name");

        jLabel3.setText("Author");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK DIRECTORY");

        jLabel4.setText("Description");

        librarytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Author", "Description"
            }
        ));
        jScrollPane1.setViewportView(librarytable);

        jButton1.setText("Add Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookDirectoryLayout = new javax.swing.GroupLayout(bookDirectory);
        bookDirectory.setLayout(bookDirectoryLayout);
        bookDirectoryLayout.setHorizontalGroup(
            bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDirectoryLayout.createSequentialGroup()
                .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDirectoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDirectoryLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookDirectoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(bookname)
                            .addComponent(description))
                        .addGap(96, 96, 96)
                        .addComponent(jButton6)
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(bookDirectoryLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookDirectoryLayout.setVerticalGroup(
            bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDirectoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDirectoryLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(bookDirectoryLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(bookDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jButton7)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jLabel6.setText("Room");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LIBRARY ROOM BOOKING");

        libraryroommaintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Room", "Slots"
            }
        ));
        jScrollPane2.setViewportView(libraryroommaintable);

        jButton3.setText("Add Slot");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setText("Slots");

        roomname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K 1", "K 2", "K 3", "K 4", "K 5" }));

        slots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8AM - 9AM", "9AM - 10AM", "10AM - 11AM", "11AM - 12PM", "12PM - 1PM", "1PM - 2PM", "2PM - 3PM", "3PM - 4PM", "4PM - 5PM", "5PM - 6PM", "6PM - 7PM", "7PM - 8PM" }));

        javax.swing.GroupLayout libraryRoomBookingLayout = new javax.swing.GroupLayout(libraryRoomBooking);
        libraryRoomBooking.setLayout(libraryRoomBookingLayout);
        libraryRoomBookingLayout.setHorizontalGroup(
            libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryRoomBookingLayout.createSequentialGroup()
                .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libraryRoomBookingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libraryRoomBookingLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(libraryRoomBookingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(28, 28, 28))
                    .addGroup(libraryRoomBookingLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(slots, 0, 174, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(libraryRoomBookingLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        libraryRoomBookingLayout.setVerticalGroup(
            libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryRoomBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9))
                .addGap(24, 24, 24)
                .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roomname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(libraryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton8)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jLayeredPaneAdms.setLayer(bookDirectory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAdms.setLayer(libraryRoomBooking, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneAdmsLayout = new javax.swing.GroupLayout(jLayeredPaneAdms);
        jLayeredPaneAdms.setLayout(jLayeredPaneAdmsLayout);
        jLayeredPaneAdmsLayout.setHorizontalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneAdmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(libraryRoomBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        jLayeredPaneAdmsLayout.setVerticalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneAdmsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(libraryRoomBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        Student_button.setText("Book Directory");
        Student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_buttonActionPerformed(evt);
            }
        });

        Course_button.setText("Room Booking");
        Course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPaneAdms)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Student_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Course_button)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Student_button, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(Course_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 105, Short.MAX_VALUE)
                .addComponent(jLayeredPaneAdms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_buttonActionPerformed
        // TODO add your handling code here:
        bookDirectory.setVisible(true);
        libraryRoomBooking.setVisible(false);
        //Dummy_JPanel.setVisible(false);
    }//GEN-LAST:event_Student_buttonActionPerformed

    private void Course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_buttonActionPerformed
        // TODO add your handling code here:
        bookDirectory.setVisible(false);
        libraryRoomBooking.setVisible(true);
        //Dummy_JPanel.setVisible(false);
    }//GEN-LAST:event_Course_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        Person pd = person_list.addNewPerson();
//
//        pd.setName(bookname.getText());
//        pd.setDesignation(roomname.getSelectedItem().toString());
//        pd.setAge(description.getText());
//        pd.setPhone(jTextField4.getText());
//        pd.setHospital(jTextField8.getText());
//        pd.setUsername(jTextField9.getText());
//        pd.setPassword(jPasswordField1.getPassword());
//
//        JOptionPane.showMessageDialog(this, "New person added.");
//
//        bookname.setText("");
//        roomname.setSelectedItem("Patient");
//        description.setText("");
//        jTextField4.setText("");
//        jTextField8.setText("");
//        jTextField9.setText("");
//        jPasswordField1.setText("");
//
//        populateTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = librarytable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to update.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) librarytable.getModel();
//        String value = model.getValueAt(selectedRowIndex, 0).toString();
//
//        for(Person ho:this.person_list.getList()) {
//            if(ho.getName().equals(value)) {
//                ho.setName(bookname.getText());
//                ho.setDesignation(roomname.getSelectedItem().toString());
//                ho.setAge(description.getText());
//                ho.setPhone(jTextField4.getText());
//                ho.setHospital(jTextField8.getText());
//                ho.setUsername(jTextField9.getText());
//                ho.setPassword(jPasswordField1.getPassword());
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Record updated.");
//
//        populateTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = librarytable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) librarytable.getModel();
//        //Community selectedCommunity = (Community)model.getValueAt(selectedRowIndex, 0);
//
//        //community_list.deleteCommunity(selectedCommunity);
//        String value1 = model.getValueAt(selectedRowIndex, 0).toString();
//
//        Person_List newList = new Person_List();
//        newList.setList(this.person_list.getList());
//
//        for(Person co:newList.getList()) {
//            if(co.getName().equals(value1)) {
//                person_list.deletePerson(co);
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Person deleted.");
//        //JOptionPane.showMessageDialog(this, model.getValueAt(selectedRowIndex, 0));
//
//        populateTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        Person pd = person_list.addNewPerson();
//
//        pd.setName(bookname.getText());
//        pd.setDesignation(roomname.getSelectedItem().toString());
//        pd.setAge(description.getText());
//        pd.setPhone(jTextField4.getText());
//        pd.setHospital(jTextField8.getText());
//        pd.setUsername(jTextField9.getText());
//        pd.setPassword(jPasswordField1.getPassword());
//
//        JOptionPane.showMessageDialog(this, "New person added.");
//
//        bookname.setText("");
//        roomname.setSelectedItem("Patient");
//        description.setText("");
//        jTextField4.setText("");
//        jTextField8.setText("");
//        jTextField9.setText("");
//        jPasswordField1.setText("");
//
//        populateTable();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = librarytable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to update.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) librarytable.getModel();
//        String value = model.getValueAt(selectedRowIndex, 0).toString();
//
//        for(Person ho:this.person_list.getList()) {
//            if(ho.getName().equals(value)) {
//                ho.setName(bookname.getText());
//                ho.setDesignation(roomname.getSelectedItem().toString());
//                ho.setAge(description.getText());
//                ho.setPhone(jTextField4.getText());
//                ho.setHospital(jTextField8.getText());
//                ho.setUsername(jTextField9.getText());
//                ho.setPassword(jPasswordField1.getPassword());
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Record updated.");
//
//        populateTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = librarytable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) librarytable.getModel();
//        //Community selectedCommunity = (Community)model.getValueAt(selectedRowIndex, 0);
//
//        //community_list.deleteCommunity(selectedCommunity);
//        String value1 = model.getValueAt(selectedRowIndex, 0).toString();
//
//        Person_List newList = new Person_List();
//        newList.setList(this.person_list.getList());
//
//        for(Person co:newList.getList()) {
//            if(co.getName().equals(value1)) {
//                person_list.deletePerson(co);
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Person deleted.");
//        //JOptionPane.showMessageDialog(this, model.getValueAt(selectedRowIndex, 0));
//
//        populateTable();
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Course_button;
    private javax.swing.JButton Student_button;
    private javax.swing.JTextField author;
    private javax.swing.JPanel bookDirectory;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPaneAdms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel libraryRoomBooking;
    private javax.swing.JTable libraryroommaintable;
    private javax.swing.JTable librarytable;
    private javax.swing.JComboBox<String> roomname;
    private javax.swing.JComboBox<String> slots;
    // End of variables declaration//GEN-END:variables
}
