/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Main;

/**
 *
 * @author aksha
 */
public class JPanel_Residential_enterprise_Admin extends javax.swing.JPanel {
    public Main Main;

    /**
     * Creates new form Admission_enterprise
     */
    public JPanel_Residential_enterprise_Admin() {
        initComponents();
        DormsJPanel.setVisible(false);
        CleaningJPanel.setVisible(false);
        this.Main = new Main();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneAdms = new javax.swing.JLayeredPane();
        DormsJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageDormsTable = new javax.swing.JTable();
        btnDecideAvailability = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbRoom = new javax.swing.JComboBox<>();
        cbAvailability = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        roomID = new javax.swing.JTextField();
        CleaningJPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        slot = new javax.swing.JComboBox<>();
        roomname = new javax.swing.JComboBox<>();
        btnManageDorms = new javax.swing.JButton();
        btnAddCleaningSlots = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        DormsJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Room");

        jLabel3.setText("Availability");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE DORMS");

        manageDormsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Room", "Availability"
            }
        ));
        jScrollPane1.setViewportView(manageDormsTable);

        btnDecideAvailability.setText("Decide Availability");
        btnDecideAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecideAvailabilityActionPerformed(evt);
            }
        });

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A 1", "A 2", "A 3", "A 4", "A 5", "B 1", "B 2", "B 3", "B 4", "B 5" }));

        cbAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jLabel4.setText("Room ID");

        roomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DormsJPanelLayout = new javax.swing.GroupLayout(DormsJPanel);
        DormsJPanel.setLayout(DormsJPanelLayout);
        DormsJPanelLayout.setHorizontalGroup(
            DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DormsJPanelLayout.createSequentialGroup()
                .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DormsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DormsJPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DormsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDecideAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DormsJPanelLayout.createSequentialGroup()
                                .addGap(0, 301, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addGap(28, 28, 28))
                            .addGroup(DormsJPanelLayout.createSequentialGroup()
                                .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbAvailability, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roomID))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(DormsJPanelLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DormsJPanelLayout.setVerticalGroup(
            DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DormsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecideAvailability)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(roomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DormsJPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DormsJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DormsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100)
                .addComponent(jButton7)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jLabel6.setText("Room");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MANAGE CLEANING SLOTS");

        jLabel16.setText("Slot");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Room", "Slot"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Add Slot");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        slot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9AM - 10AM", "10AM - 11AM", "11AM - 12PM", "12PM - 1PM", "2PM - 3PM", "3PM - 4PM", "4PM - 5PM" }));

        roomname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A 1", "A 2", "A 3", "A 4", "A 5", "B 1", "B 2", "B 3", "B 4", "B 5" }));

        javax.swing.GroupLayout CleaningJPanelLayout = new javax.swing.GroupLayout(CleaningJPanel);
        CleaningJPanel.setLayout(CleaningJPanelLayout);
        CleaningJPanelLayout.setHorizontalGroup(
            CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CleaningJPanelLayout.createSequentialGroup()
                .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CleaningJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CleaningJPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CleaningJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CleaningJPanelLayout.createSequentialGroup()
                                .addComponent(slot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(jButton9)
                                .addGap(28, 28, 28))
                            .addGroup(CleaningJPanelLayout.createSequentialGroup()
                                .addComponent(roomname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(CleaningJPanelLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CleaningJPanelLayout.setVerticalGroup(
            CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CleaningJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9))
                .addGap(3, 3, 3)
                .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roomname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CleaningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(slot, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(84, 84, 84))
        );

        jLayeredPaneAdms.setLayer(DormsJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAdms.setLayer(CleaningJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneAdmsLayout = new javax.swing.GroupLayout(jLayeredPaneAdms);
        jLayeredPaneAdms.setLayout(jLayeredPaneAdmsLayout);
        jLayeredPaneAdmsLayout.setHorizontalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneAdmsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DormsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(CleaningJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        jLayeredPaneAdmsLayout.setVerticalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneAdmsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DormsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(CleaningJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        btnManageDorms.setText("Manage Dorms");
        btnManageDorms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDormsActionPerformed(evt);
            }
        });

        btnAddCleaningSlots.setText("Add cleaning slots");
        btnAddCleaningSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCleaningSlotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPaneAdms)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnManageDorms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(btnAddCleaningSlots)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageDorms, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnAddCleaningSlots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 28, Short.MAX_VALUE)
                .addComponent(jLayeredPaneAdms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDormsActionPerformed
        // TODO add your handling code here:
        DormsJPanel.setVisible(true);
        CleaningJPanel.setVisible(false);
        //Dummy_JPanel.setVisible(false);
    }//GEN-LAST:event_btnManageDormsActionPerformed

    private void btnAddCleaningSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCleaningSlotsActionPerformed
        // TODO add your handling code here:
        DormsJPanel.setVisible(false);
        CleaningJPanel.setVisible(true);
        //Dummy_JPanel.setVisible(false);
    }//GEN-LAST:event_btnAddCleaningSlotsActionPerformed

    private void btnDecideAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecideAvailabilityActionPerformed

 String RoomID = roomID.getText();
 String CbRoom = cbRoom.getSelectedItem().toString();
 String roomAvailability = cbAvailability.getSelectedItem().toString();

//try {
//            int roomID = checkRoomExists(cbRoom);
//            if(roomID != 0)
//            {
//                JOptionPane.showMessageDialog(this, "Username already exists!");
//                
//                return;
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//        }

        try{
            Main.executeInsert("INSERT INTO residential_table ( roomID , roomName, roomAvailability) VALUES ('"+RoomID+"' , '"+CbRoom+"', '"+roomAvailability+"')");
                JOptionPane.showMessageDialog(this, "Slot Added successfully!");
                
            
         
            
        }
        catch(Exception e){
        Logger.getLogger(JPanel_Admission_enterprise_Admin.class.getName()).log(Level.SEVERE, null, e);        }
//JPanel_Admission_enterprise_Admin
      



        // TODO add your handling code here:
//        Person pd = person_list.addNewPerson();
//
//        pd.setName(jTextField1.getText());
//        pd.setDesignation(slot.getSelectedItem().toString());
//        pd.setAge(jTextField3.getText());
//        pd.setPhone(jTextField4.getText());
//        pd.setHospital(jTextField8.getText());
//        pd.setUsername(jTextField9.getText());
//        pd.setPassword(jPasswordField1.getPassword());
//
//        JOptionPane.showMessageDialog(this, "New person added.");
//
//        jTextField1.setText("");
//        slot.setSelectedItem("Patient");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField8.setText("");
//        jTextField9.setText("");
//        jPasswordField1.setText("");
//
//        populateTable();

    }//GEN-LAST:event_btnDecideAvailabilityActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = dormstable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to update.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) dormstable.getModel();
//        String value = model.getValueAt(selectedRowIndex, 0).toString();
//
//        for(Person ho:this.person_list.getList()) {
//            if(ho.getName().equals(value)) {
//                ho.setName(jTextField1.getText());
//                ho.setDesignation(slot.getSelectedItem().toString());
//                ho.setAge(jTextField3.getText());
//                ho.setPhone(jTextField4.getText());
//                ho.setHospital(jTextField8.getText());
//                ho.setUsername(jTextField9.getText());
//                ho.setPassword(jPasswordField1.getPassword());
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Record updated.");
//
//        populateTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = dormstable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) dormstable.getModel();
//        //Community selectedCommunity = (Community)model.getValueAt(selectedRowIndex, 0);
//
//        //community_list.deleteCommunity(selectedCommunity);
//        String value1 = model.getValueAt(selectedRowIndex, 0).toString();
//
//        Person_List newList = new Person_List();
//        newList.setList(this.person_list.getList());
//
//        for(Person co:newList.getList()) {
//            if(co.getName().equals(value1)) {
//                person_list.deletePerson(co);
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Person deleted.");
//        //JOptionPane.showMessageDialog(this, model.getValueAt(selectedRowIndex, 0));
//
//        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        Person pd = person_list.addNewPerson();
//
//        pd.setName(jTextField1.getText());
//        pd.setDesignation(slot.getSelectedItem().toString());
//        pd.setAge(jTextField3.getText());
//        pd.setPhone(jTextField4.getText());
//        pd.setHospital(jTextField8.getText());
//        pd.setUsername(jTextField9.getText());
//        pd.setPassword(jPasswordField1.getPassword());
//
//        JOptionPane.showMessageDialog(this, "New person added.");
//
//        jTextField1.setText("");
//        slot.setSelectedItem("Patient");
//        jTextField3.setText("");
//        jTextField4.setText("");
//        jTextField8.setText("");
//        jTextField9.setText("");
//        jPasswordField1.setText("");
//
//        populateTable();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = dormstable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to update.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) dormstable.getModel();
//        String value = model.getValueAt(selectedRowIndex, 0).toString();
//
//        for(Person ho:this.person_list.getList()) {
//            if(ho.getName().equals(value)) {
//                ho.setName(jTextField1.getText());
//                ho.setDesignation(slot.getSelectedItem().toString());
//                ho.setAge(jTextField3.getText());
//                ho.setPhone(jTextField4.getText());
//                ho.setHospital(jTextField8.getText());
//                ho.setUsername(jTextField9.getText());
//                ho.setPassword(jPasswordField1.getPassword());
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Record updated.");
//
//        populateTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = dormstable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) dormstable.getModel();
//        //Community selectedCommunity = (Community)model.getValueAt(selectedRowIndex, 0);
//
//        //community_list.deleteCommunity(selectedCommunity);
//        String value1 = model.getValueAt(selectedRowIndex, 0).toString();
//
//        Person_List newList = new Person_List();
//        newList.setList(this.person_list.getList());
//
//        for(Person co:newList.getList()) {
//            if(co.getName().equals(value1)) {
//                person_list.deletePerson(co);
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Person deleted.");
//        //JOptionPane.showMessageDialog(this, model.getValueAt(selectedRowIndex, 0));
//
//        populateTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void roomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CleaningJPanel;
    private javax.swing.JPanel DormsJPanel;
    private javax.swing.JButton btnAddCleaningSlots;
    private javax.swing.JButton btnDecideAvailability;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageDorms;
    private javax.swing.JComboBox<String> cbAvailability;
    private javax.swing.JComboBox<String> cbRoom;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPaneAdms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable manageDormsTable;
    private javax.swing.JTextField roomID;
    private javax.swing.JComboBox<String> roomname;
    private javax.swing.JComboBox<String> slot;
    // End of variables declaration//GEN-END:variables
}
