/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author aksha
 */
public class JPanel_Admission_enterprise_Officer extends javax.swing.JPanel {

    /**
     * Creates new form Admission_enterprise
     */
    public JPanel_Admission_enterprise_Officer() {
        initComponents();
        //StudentJPanel.setVisible(false);
        CourseJPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneAdms = new javax.swing.JLayeredPane();
        CourseJPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        couseid = new javax.swing.JTextField();
        Course_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        CourseJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Name");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("COURSE DIRECTORY");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Course Name"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Add Course");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        couseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couseidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CourseJPanelLayout = new javax.swing.GroupLayout(CourseJPanel);
        CourseJPanel.setLayout(CourseJPanelLayout);
        CourseJPanelLayout.setHorizontalGroup(
            CourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseJPanelLayout.createSequentialGroup()
                .addGroup(CourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CourseJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CourseJPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CourseJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(28, 28, 28))
                    .addGroup(CourseJPanelLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CourseJPanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(couseid, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)))
                .addContainerGap())
        );
        CourseJPanelLayout.setVerticalGroup(
            CourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CourseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(couseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton8)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jLayeredPaneAdms.setLayer(CourseJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneAdmsLayout = new javax.swing.GroupLayout(jLayeredPaneAdms);
        jLayeredPaneAdms.setLayout(jLayeredPaneAdmsLayout);
        jLayeredPaneAdmsLayout.setHorizontalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CourseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jLayeredPaneAdmsLayout.setVerticalGroup(
            jLayeredPaneAdmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAdmsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CourseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        Course_button.setText("Course details");
        Course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPaneAdms)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 572, Short.MAX_VALUE)
                .addComponent(Course_button)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Course_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 136, Short.MAX_VALUE)
                .addComponent(jLayeredPaneAdms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_buttonActionPerformed
        // TODO add your handling code here:
        //StudentJPanel.setVisible(false);
        CourseJPanel.setVisible(true);
        //Dummy_JPanel.setVisible(false);
    }//GEN-LAST:event_Course_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        Person pd = person_list.addNewPerson();
//
//        pd.setName(StudentID.getText());
//        pd.setDesignation(jComboBox1.getSelectedItem().toString());
//        pd.setAge(age.getText());
//        pd.setPhone(gender.getText());
//        pd.setHospital(phone.getText());
//        pd.setUsername(email.getText());
//        pd.setPassword(address.getPassword());
//
//        JOptionPane.showMessageDialog(this, "New person added.");
//
//        StudentID.setText("");
//        jComboBox1.setSelectedItem("Patient");
//        age.setText("");
//        gender.setText("");
//        phone.setText("");
//        email.setText("");
//        address.setText("");
//
//        populateTable();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = studenttable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to update.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) studenttable.getModel();
//        String value = model.getValueAt(selectedRowIndex, 0).toString();
//
//        for(Person ho:this.person_list.getList()) {
//            if(ho.getName().equals(value)) {
//                ho.setName(StudentID.getText());
//                ho.setDesignation(jComboBox1.getSelectedItem().toString());
//                ho.setAge(age.getText());
//                ho.setPhone(gender.getText());
//                ho.setHospital(phone.getText());
//                ho.setUsername(email.getText());
//                ho.setPassword(address.getPassword());
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Record updated.");
//
//        populateTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        int selectedRowIndex = studenttable.getSelectedRow();
//
//        if(selectedRowIndex < 0){
//            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
//            return;
//        }
//
//        DefaultTableModel model = (DefaultTableModel) studenttable.getModel();
//        //Community selectedCommunity = (Community)model.getValueAt(selectedRowIndex, 0);
//
//        //community_list.deleteCommunity(selectedCommunity);
//        String value1 = model.getValueAt(selectedRowIndex, 0).toString();
//
//        Person_List newList = new Person_List();
//        newList.setList(this.person_list.getList());
//
//        for(Person co:newList.getList()) {
//            if(co.getName().equals(value1)) {
//                person_list.deletePerson(co);
//                break;
//            }else{
//                continue;
//            }
//
//        }
//
//        JOptionPane.showMessageDialog(this, "Person deleted.");
//        //JOptionPane.showMessageDialog(this, model.getValueAt(selectedRowIndex, 0));
//
//        populateTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void couseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couseidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CourseJPanel;
    private javax.swing.JButton Course_button;
    private javax.swing.JTextField couseid;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPaneAdms;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
