/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.City;
import model.City_List;
import model.Community;
import model.Community_List;
import model.Encounter;
import model.Encounter_History;
import model.Hospital;
import model.Hospital_List;
import model.House;
import model.House_List;
import model.Person;
import model.Person_List;

/**
 *
 * @author aksha
 */
public class Login_JFrame_ini extends javax.swing.JFrame {

    /**
     * Creates new form Login_JFrame_ini
     */
    
    City city;
    City_List city_list;
    
    Community community;
    Community_List community_list;
    
    House house;
    House_List house_list;
    
    Hospital hospital;
    Hospital_List hospital_list;
    
    Encounter encounter;
    Encounter_History encounter_history;
    
    Person person;
    Person_List person_list;
    
    
    public Login_JFrame_ini(City_List city_list_i, Community_List community_list_i, House_List house_list_i, Hospital_List hospital_list_i, Encounter_History encounter_history_i, Person_List person_list_i) {
        initComponents();
        
        city = new City();
        city_list = new City_List();
        city_list.setList(city_list_i.getList());
        
        community = new Community();
        community_list = new Community_List();
        community_list.setList(community_list_i.getList());
        
        house = new House();
        house_list = new House_List();
        house_list.setList(house_list_i.getList());
        
        hospital = new Hospital();
        hospital_list = new Hospital_List();
        hospital_list.setList(hospital_list_i.getList());
        
        encounter = new Encounter();
        encounter_history = new Encounter_History();
        encounter_history.setList(encounter_history_i.getList());
        
        person = new Person();
        person_list = new Person_List();
        person_list.setList(person_list_i.getList());
        
    }
    
    
    
    public Login_JFrame_ini() {
        initComponents();
        city = new City();
        city_list = new City_List();
        community = new Community();
        community_list = new Community_List();
        house = new House();
        house_list = new House_List();
        hospital = new Hospital();
        hospital_list = new Hospital_List();
        encounter = new Encounter();
        encounter_history = new Encounter_History();
        person = new Person();
        person_list = new Person_List();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Control_Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Work_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(102, 102, 102));

        Control_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Control_PanelLayout = new javax.swing.GroupLayout(Control_Panel);
        Control_Panel.setLayout(Control_PanelLayout);
        Control_PanelLayout.setHorizontalGroup(
            Control_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Control_PanelLayout.setVerticalGroup(
            Control_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_PanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButton1)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(Control_Panel);

        Work_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainLogin.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout Work_PanelLayout = new javax.swing.GroupLayout(Work_Panel);
        Work_Panel.setLayout(Work_PanelLayout);
        Work_PanelLayout.setHorizontalGroup(
            Work_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Work_PanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                .addContainerGap())
        );
        Work_PanelLayout.setVerticalGroup(
            Work_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Work_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(Work_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginJPanel loginJPanel = new LoginJPanel(city_list, community_list, house_list, hospital_list, encounter_history, person_list);
        jSplitPane1.setRightComponent(loginJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_JFrame_ini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_JFrame_ini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Control_Panel;
    private javax.swing.JPanel Work_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
